apiVersion: v1
kind: Service
metadata:
  namespace: "leaf-image-management-system"
  labels:
    app: "kafka-broker"
  name: "kafka-service"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: kafka-port-1
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: kafka-port-2
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: "kafka-broker"
