apiVersion: v1
kind: Service
metadata:
  name: mongodb-producer
  namespace: leaf-image-management-system
spec:
  selector:
    name: mongodb-producer
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017
