apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-producer
  namespace: leaf-image-management-system
  labels:
    name: mongodb-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-producer
  template:
    metadata:
      labels:
        name: mongodb-producer
    spec:
      containers:
        - name: mongodb-producer-container
          image: 12221994/producer_plant_db:latest
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
