apiVersion: v1
kind: Service
metadata:
  name: mongodb-producer
  namespace: leaf-image-management-system
spec:
  selector:
    name: mongodb-producer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
