apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "leaf-image-management-system"
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
          resources:
            requests:
              memory: 2048Mi
              cpu: 800m
            limits:
              memory: 4096Mi
              cpu: 900m
