apiVersion: v1
kind: Service
metadata:
  name: "leaf-disease-recognizer"
  namespace: "leaf-image-management-system"
spec:
  selector:
    name: "leaf-disease-recognizer"
  type: NodePort
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: job-port
