apiVersion: v1
kind: Service
metadata:
  name: "image-api"
  namespace: "leaf-image-management-system"
  labels:
    app: "image-api"
spec:
  selector:
    app: "image-api"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: api-port
    - name: metrics
      protocol: TCP
      port: 8050
      targetPort: 8050
