apiVersion: v1
kind: Service
metadata:
  name: "image-api"
  namespace: "leaf-image-management-system"
spec:
  selector:
    name: "image-api"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: api-port
    - protocol: TCP
      port: 8050
      targetPort: 8050
      name: prometheus-port
