apiVersion: v1
kind: Service
metadata:
  name: "image-analyzer-api"
  namespace: "leaf-image-management-system"
spec:
  selector:
    name: "image-analyzer-api"
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 30080
      protocol: TCP
