apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-consumer
  namespace: leaf-image-management-system
  labels:
    name: mongodb-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-consumer
  template:
    metadata:
      labels:
        name: mongodb-consumer
    spec:
      containers:
        - name: mongodb-consumer-container
          image: 12221994/consumer_plant_db:latest
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "1536Mi"
              cpu: "500m"
