apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: "metrics"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus_Server
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-kube-prometheus-prometheus.metrics.svc.cluster.local:9090
        isDefault: true
