apiVersion: apps/v1
kind: Deployment
metadata:
  name: "db-synchronizer"
  namespace: "leaf-image-management-system"
  labels:
    name: "db-synchronizer"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "db-synchronizer"
  template:
    metadata:
      labels:
        name: "db-synchronizer"
    spec:
      containers:
        - name: "db-synchronizer"
          image: "12221994/db_synchronizer_job:latest"
          env:
            - name: ENV
              value: "stg"
          ports:
            - containerPort: 5050
            - containerPort: 8050
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
