apiVersion: v1
kind: Service
metadata:
  name: "db-synchronizer"
  namespace: "leaf-image-management-system"
spec:
  selector:
    name: "db-synchronizer"
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: job-port
    - protocol: TCP
      port: 8050
      targetPort: 8050
      name: prometheus-port
