apiVersion: v1
kind: Service
metadata:
  name: "db-synchronizer"
  namespace: "leaf-image-management-system"
  labels:
    app: "db-synchronizer"
spec:
  selector:
    app: "db-synchronizer"
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: job-port
    - name: metrics
      protocol: TCP
      port: 8050
      targetPort: 8050
