apiVersion: v1
kind: Service
metadata:
  name: "camera"
  namespace: "leaf-image-management-system"
spec:
  selector:
    name: "camera"
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: job-port
