apiVersion: v1
kind: Service
metadata:
  name: "image-analyzer-api"
  namespace: "leaf-image-management-system"
spec:
  selector:
    name: "image-analyzer-api"
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
