apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: image-api-backendconfig
  namespace: leaf-image-management-system
spec:
  healthCheck:
    requestPath: /ping
    port: 8080
    type: HTTP
