{
 "title": "Leaf Image Management System",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Batch processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of images processed and transferred by the batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service) (db_synchronizer_job_image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of images processed and transferred by the batch, kB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service) (db_synchronizer_job_image_size) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stream processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of images processed and transferred by the stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(service) (image_api_image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of images processed and transferred by the stream, kB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(service) (image_api_image_size) / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}